server:
  port: 8888
  # 开启优雅下线
  shutdown: graceful

spring:
  application:
    name: demo-auth
  main:
    allow-bean-definition-overriding: on
  # 设置优雅下线超时时间
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    #将执行的sql打印出来，生产需关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl