apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deploy
  namespace: default
spec:
  replicas: 1 #副本数量
  revisionHistoryLimit: 3 #设置保留的历史版本个数，默认是 10
  minReadySeconds: 0 #设置 pod 准备就绪的最小秒数（需要估一个比较合理的值，从容器启动到应用正常提供服务）
  strategy:
    type: RollingUpdate #滚动更新
    rollingUpdate:
      maxSurge: 30% #更新时允许最大激增的容器数，可以是个数，也可以是百分比（默认 replicas 的 1/4 向上取整）
      maxUnavailable: 30% #更新时允许最大 unavailable 容器数，可以是个数，也可以是百分比（默认 replicas 的 1/4 向上取整）
  selector:
    matchLabels:
      name: demo-k8s
  template:
    metadata:
      labels:
        name: demo-k8s
    spec:
      containers:
        - name: demo-k8s-container
          image: demo-k8s:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests: #最小资源配置
              cpu: 300m #代表0.3CPU
              memory: 300Mi
            limits: #最大资源配置
              cpu: 500m #代表0.5CPU
              memory: 500Mi

      restartPolicy: Always #Pod的重启策略：Always、OnFailure、Never

---

apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
  namespace: default
spec:
  selector:
    name: demo-k8s
  type: NodePort
  ports:
    - name: demo-k8s-port
      protocol: TCP
      port: 8888  #service端口
      targetPort: 8888 #容器端口
      nodePort: 31888 #对外访问端口

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-k8s-hpa
  namespace: default
spec:
  scaleTargetRef: #指定需要管理的 Deployment/ReplicaSet 的名字
    apiVersion: apps/v1
    kind: Deployment
    name: demo-k8s-deploy
  minReplicas: 1 #pod可伸缩最小范围
  maxReplicas: 3 #pod可伸缩最大范围
  metrics:
    # Resource类型指标
    - type: Resource
      resource:
        name: cpu # CPU指标
        target:
          type: Utilization # Utilization类型的目标值，Resource类型的指标支持Utilization和AverageValue类型的目标值
          averageUtilization: 50  # 指定 CPU 使用率（自动扩容/缩容的触发条件）
    - type: Resource
      resource:
        name: memory  # 内存指标
        target:
          type: Utilization # Utilization类型的目标值，Resource类型的指标支持Utilization和AverageValue类型的目标值
          averageUtilization: 60  # 指定内存使用率（自动扩容/缩容的触发条件）
    # Pods类型指标
    - type: Pods
      pods:
        metric:
          name: packets-per-second  # 每秒数据包
        target:
          type: AverageValue  # AverageValue类型的目标值，Pods指标类型下只支持AverageValue类型的目标值
          averageValue: 1k  # 指定每秒数据包平均值（自动扩容/缩容的触发条件）
    # Object类型指标
    - type: Object
      object:
        # 监控指标的对象描述，指标数据来源于该对象
        describedObject:
          apiVersion: networking.k8s.io/v1beta1
          kind: Ingress
          name: main-route
        metric:
          name: requests-per-second # 每秒请求数
        target:
          type: Value # Value类型的目标值，Object类型的指标只支持Value和AverageValue类型的目标值
          value: 10k  # 每秒请求数平均值（自动扩容/缩容的触发条件）