# 不分库、分表
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: test
        password: test
    sharding:
      tables:
        temp_order:
          # 分表策略
          actual-data-nodes: ds0.temp_order_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: temp_order_$->{id % 2}
    # 开启sql显示
    props:
      sql:
        show: on