server:
  port: 8888
  # 开启优雅下线
  shutdown: graceful

spring:
  application:
    name: demo-rocketmq
  # 设置优雅下线超时时间
  lifecycle:
    timeout-per-shutdown-phase: 30s

rocketmq:
  # NameServer 地址
  name-server: localhost:9876
  producer:
    # 发送同一类消息设置为同一个 group，保证唯一默认不需要设置，rocketmq 会使用 ip@pid（pid代表jvm名字）作为唯一标识
    group: ${spring.application.name}
    # 消息最大长度，默认：1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认：3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认：2
    retry-times-when-send-failed: 2